### ISSUE TITLE
loco position deck attachment on crazyflie 2.0  

### ISSUE THREAD

**Issue by sarwadenj** [bitcraze/crazyflie2-exp-template-electronics#1]
Hi,

I saw the loco position deck schematics on below mentioned site 
https://wiki.bitcraze.io/projects:lps:deck

As mentioed on site The Loco Positioning deck is designed to be installed on the Crazyflie 2.0 deck port.
https://github.com/bitcraze/crazyflie2-exp-template-electronics

So in this crazyflie 2.0 design need to attach loco positioning deck.
Please give clear view of design.

Thanks You.

**Comment by ataffanel** [comment]
Hi,

I do not understand your question but it is for sure off-topic with the Crazyflie 2.0 deck Kicad template.

The Loco positioning system is still in early access, you will find some documentation for it on the wiki: https://wiki.bitcraze.io/doc:lps:index. If you want to discuss further about the architecture and the way the LPS work I will gladly answer you on the forum: https://forum.bitcraze.io/viewforum.php?f=16

/Arnaud

**Comment by sarwadenj** [comment]
Hi @ataffanel,

Can we put Loco position deck on this crazyflie 2.0 board.

Thanks.

**Comment by ataffanel** [comment]
Hi @sarwadenj, if by "this crazyflie 2.0 board" you mean the template contained in this git repos: this template has been used by us to make the LPS deck. The deck is described on the bitcraze website and is already available: https://www.bitcraze.io/loco-pos-deck/

/Arnaud

**Comment by sarwadenj** [comment]
Hi @ataffanel 
Where should i look for BOM for crazyflie 2.0 board.

Thanks.

**Comment by ataffanel** [comment]
Hi @sarwadenj, This is still off-topic for this repos. Can you please ask your question in the forum so that I can answer you there (https://forum.bitcraze.io).

**Comment by sarwadenj** [comment]
@ataffanel  ok 
Thanks.
